<?php
require_once(get_template_directory().'/php-functions/php-add-scripts-styles.php');
require_once(get_template_directory().'/php-functions/php-options-page.php');
require_once(get_template_directory().'/php-functions/php-remove-editor.php');
require_once(get_template_directory().'/php-functions/php-allow-svg.php');
require_once(get_template_directory().'/php-functions/php-admin-sticky-update.php');
require_once(get_template_directory().'/php-functions/php-register-menus.php');
require_once(get_template_directory().'/php-functions/php-register-doctors-post-type.php');
require_once(get_template_directory().'/php-functions/php-register-offer-post-type.php');
require_once(get_template_directory().'/php-functions/php-disable-comments.php');
require_once(get_template_directory().'/php-functions/php-register-med_title-taxonomy.php');
require_once(get_template_directory().'/php-functions/php-register-department-taxonomy.php');
require_once(get_template_directory().'/php-functions/php-register-offer-category-taxonomy.php');
require_once(get_template_directory().'/php-functions/php-specialists-ajax.php');